name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --only dev
    - name: Lint with pylint
      run: |
        poetry run pylint --fail-under=9 $(git ls-files '*.py')
    - name: Check formatting with black
      run: |
        poetry run black . --diff 
    - name: Install poetry dependencies w/o numba
      run: |
        poetry install --no-root
        export NPP_USE_NUMBA='FALSE'
    - name: Test with pytest w/o numba
      run: |
        poetry run pytest
    - name: Install poetry dependencies w/numba
      run: |
        poetry install --all-extras --no-root
        export NPP_USE_NUMBA='TRUE'
    - name: Test with pytest w/numba
      run: |
        poetry run pytest
    - name: Build wheel via poetry
      run: poetry build --format=wheel
    - name: Upload Wheel Artifact
      uses: actions/upload-artifact@v3
      with:
        name: wheel-artifact
        path: ./dist/numba_pokemon_prngs-0.1.0-py3-none-any.whl

  # taken from https://github.com/kernelkit/infix/blob/main/.github/workflows/build.yml
  release:

    name: Upload Latest Build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - uses: pyTooling/Actions/releaser@main
        with:
          tag: latest
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: artifact/*
      - name: Summary
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          # Latest Build Complete! :rocket:
          
          For the public download links of these build artifacts, please see:
           <https://github.com/Lincoln-LM/numba_pokemon_prngs/releases/tag/latest>
          EOF
